Show menu
CraftAcademy/slowfood-client-team-2-april-2020 pull request #2
Opened 2020-05-05 11:38 UTC by kermit-klein

[PT LINK](https://www.pivotaltracker.com/story/show/172642044)

Client can show menu list through axios get request(did test with mock request)
Client can connect with API to show plain text of menu items
cy:run script added for semaphore

2020-05-05 12:05 UTC, ViaMarcus commented on cypress/integration/userCanSeeMenu.feature.js
> +  });
Should have newline

2020-05-05 14:47 UTC, oliverochman requested changes

2020-05-05 14:47 UTC, oliverochman commented on cypress/fixtures/menu_list_index.json
> +  "items": [
this should be the same as the model name in the backend

2020-05-05 14:47 UTC, oliverochman commented on cypress/integration/userCanSeeMenu.feature.js
> +  it("shows one menu item", () => {
duplicate naming of it block

`it("shows another menu item"`

2020-05-05 14:47 UTC, oliverochman commented on cypress/integration/userCanSeeMenu.feature.js
> +    cy.get("#menuitem-2").within(() => {
not a fan of "#menuitem"

please use "#menu-item" instead

2020-05-05 14:47 UTC, oliverochman commented on src/components/ShowMenu.jsx
> +    let headers = {
do not think you need to specify these headers if you do not add anything else to them

2020-05-05 14:47 UTC, oliverochman commented on src/components/ShowMenu.jsx
> +    axios.get("/menu_items", { headers: headers }).then((response) => {
please use `try, catch` instead of using `.then`

old JS syntax

2020-05-05 14:47 UTC, oliverochman commented on src/components/ShowMenu.jsx
> +export class ShowMenu extends Component {
why `ShowMenu` and not just `Menu`?

2020-05-05 14:47 UTC, oliverochman commented on src/components/ShowMenu.jsx
> +      menu = menuList.map((k) => {
you need to change `k` to something more descriptive

perhaps `item`

2020-05-06 08:08 UTC, oliverochman approved these changes

2020-05-06 08:08 UTC, merged